#!/bin/bash
#récupère la valeur de luminosité
lum=$(cat /sys/class/backlight/intel_backlight/brightness)
lum_max=$(cat /sys/class/backlight/intel_backlight/max_brightness)

if [ $1 = "inc" ]
then
	test=$(($lum+$2))
	if [ "$test" -le $lum_max ]
	then
		lum=$(($lum+$2))
		echo $lum > /sys/class/backlight/intel_backlight/brightness
	fi
fi

if [ $1 = "dec" ]
then
	test=$(($lum-$2))
	if [ "$test" -ge "0" ]
	then
		lum=$(($lum-$2))
		echo $lum > /sys/class/backlight/intel_backlight/brightness
	fi
fi
