#!/bin/bash
#recupere la valeur de luminosite
lum=$(cat /sys/class/backlight/intel_backlight/brightness)
#recupere la valeur maximum de la luminosite
lum_max=$(cat /sys/class/backlight/intel_backlight/max_brightness)

#si l'argument 1 est inc (pour incremente
if [ $1 = "--increase" ] || [ $1 = "-i" ]
then
	#on test voir si la luminosite actuelle + ceux que l'ont veut rajoute ne depasse pas la luminosite max
	test=$(echo "$2/100" | bc -l)
	test=$(echo "$test*$lum_max" | bc -l)
	lum_total=$(echo "$test+$lum" | bc -l)	
	lum_total=$(echo $lum_total | cut -d. -f1)	
	if [ "$lum_total" -le "$lum_max" ]
	then
		# On ajoute la valeur a la luminosité actuelle
		lum=$lum_total
		#On erit dans le fichier suivant la nouvelle valeur de la luminosite
		echo "$lum" > /sys/class/backlight/intel_backlight/brightness
	else
		lum=$lum_max
		echo $lum > /sys/class/backlight/intel_backlight/brightness
	fi
fi


#si l'argument 1 est dec (pour decremente)
if [ $1 = "--decrease" ] || [ $1 = "-d" ]
then
	#on test voir si la luminosite actuelle - ceux que l'ont veut enleve pour ne pas alle dans le negatif
	test=$(echo "$2/100" | bc -l)
	test=$(echo "$test*$lum_max" | bc -l)
	lum_total=$(echo "$lum-$test" | bc -l)
	lum_total=$(echo $lum_total | cut -d. -f1)	
	if [ "$lum_total" -ge  "0" ]
	then
		# On enleve la valeur de la luminosite actuelle
		lum=$lum_total
		echo $lum > /sys/class/backlight/intel_backlight/brightness
		#On erit dans le fichier suivant la nouvelle valeur de la luminosite
	else
		lum=0
		echo $lum > /sys/class/backlight/intel_backlight/brightness
	fi
fi

if [ $1 = "--help" ] || [ $1 = "-h" ]
then
     echo -n "Utilisation : light [OPTION...] <VALEUR>\n\n" #Affichage de la premiere ligne de l'aide
     echo -n "-i , --increase         in "    
fi

if [ $1 = "--modify" ] || [ $1 = "-m" ]
then
	if [ $2  -ge "0" ]  && [ $2 -le $lum_max ]
	then
		echo $2 > /sys/class/backlight/intel_backlight/brightness
	fi
fi

